package com.hospital.backend.rules;
dialect  "mvel"
import com.hospital.backend.Models.*
import java.util.List
import java.util.Random
import java.util.ArrayList;
global com.hospital.backend.Models.Schedule schedule;

rule "Complete Shifts"
   when $user : User(((schedule.getNoHoursMonth8H($user)+8)<=(schedule.getNoWorkingDays()*8)));
//         $day: Day(isDateValid()==false) from schedule.selectDayWithShift1($user,ShiftTypes.SHORT.getValue(),ShiftTypes.MORNING.getValue());
    then
//       while((schedule.getNoHoursMonth($user)+8)<=(schedule.getNoWorkingDays()*8)){
            Day day1 =schedule.getDayWithoutUser($user);
            List shifts = day1.getShifts();
            Shift newShift = new Shift();
            newShift.setDay(day1);
            newShift.setUser($user);
            ShiftTypes shiftType= schedule.getLessShifts($user);
            newShift.setType(shiftType.getValue());
            shifts.add(newShift);
            day1.setShifts(shifts);
            schedule.setSpecificDay(day1);
            drools.getKieRuntime().setGlobal("schedule", schedule);
            update($user);
//            }
end
