package com.hospital.backend.rules;
dialect  "mvel"
import com.hospital.backend.Models.*
import java.util.List;
global com.hospital.backend.Models.Schedule schedule;

rule "Complete shifts"
lock-on-active
    when $user : User(!schedule.checkForCompleteUser($user,40).isEmpty());
    then
    while(!schedule.checkForCompleteUser($user,40).isEmpty()){

        Day day =  schedule.selectDayUser($user,schedule.checkForCompleteUser($user,40));
        List shifts = day.getShifts();
        Shift newShift = new Shift();
        newShift.setDay(day);
        newShift.setUser($user);
        newShift.setType(ShiftTypes.SHORT.getValue());
        shifts.add(newShift);
        day.setShifts(shifts);
        schedule.setSpecificDay(day);
        drools.getKieRuntime().setGlobal("schedule", schedule);
    }


end
