package com.hospital.backend.rules;
import java.time.DayOfWeek;
import com.hospital.backend.Models.*;
import java.time.LocalDate
import java.util.ArrayList
import java.util.Arrays
import java.util.List;
import java.util.Map
import java.util.Collections;

global java.util.List users;
global com.hospital.backend.Models.Schedule schedule;

dialect  "mvel"

dialect "java"

declare enum DaysOfWeek
   SUN("Sunday"),MON("Monday"),TUE("Tuesday"),WED("Wednesday"),THU("Thursday"),FRI("Friday"),SAT("Saturday");
    fullName : String
end


rule "Add night shifts"
//agenda-group "Generate Shifts"
salience 10
lock-on-active
    when
        $day: Day(getNoShifts(ShiftTypes.NIGHT.getValue())<2)
        $nextDay: Day(date==$day.date.plusDays(1) || $day.checkIfLast())

    then

       List shiftList = $day.setNightShifts(schedule,users,2,ShiftTypes.NIGHT.getValue(),$nextDay);
       if(!$day.checkIfLast()){
           $nextDay.setFreeDays(shiftList);
           schedule.setSpecificDay($nextDay);
           update($nextDay);
       }

        schedule.setSpecificDay($day);
        update($day);
        drools.getKieRuntime().setGlobal("schedule",schedule);
end
rule "Add morning shifts"
salience 5
lock-on-active
    when
        $day: Day(getNoShifts(ShiftTypes.MORNING.getValue())<4)
    then

        $day.setNoShifts(schedule,users,4,ShiftTypes.MORNING.getValue());
        schedule.setSpecificDay($day);

        update($day);
        drools.getKieRuntime().setGlobal("schedule",schedule);


end

