package com.hospital.backend.rules;
dialect  "mvel"
import com.hospital.backend.Models.*
import java.util.List;
global com.hospital.backend.Models.Schedule schedule;


rule "Replace shifts 5"
salience 10
    when $user : User(((schedule.getNoHoursMonth($user)+8)<=(schedule.getNoWorkingDays()*8))&& ((schedule.getNoWorkingDays()*8)-schedule.getNoHoursMonth($user))%4==0);
//         $day: Day(isDateValid()==false) from schedule.selectDayWithShift1($user,ShiftTypes.SHORT.getValue(),ShiftTypes.MORNING.getValue());
    then
//       while((schedule.getNoHoursMonth($user)+8)<=(schedule.getNoWorkingDays()*8)){
            Day dayWithoutUser =schedule.getDayWithoutUser($user);
            List shifts = dayWithoutUser.getShifts();
            Shift newShift = new Shift();
            newShift.setDay(dayWithoutUser);
            newShift.setUser($user);
            newShift.setType(ShiftTypes.SHORT.getValue());
            shifts.add(newShift);
            dayWithoutUser.setShifts(shifts);
            schedule.setSpecificDay(dayWithoutUser);
            drools.getKieRuntime().setGlobal("schedule", schedule);
            update($user);
//            }


end

rule "Replace shifts 4"
salience 5
    when $user : User(((schedule.getNoHoursMonth($user)+4)<=(schedule.getNoWorkingDays()*8)) && ((schedule.getNoWorkingDays()*8)-schedule.getNoHoursMonth($user))%4==0);
         $day: Day(isDateValid()) from schedule.selectDayWithShift($user,ShiftTypes.SHORT.getValue(),ShiftTypes.MORNING.getValue());
    then
//        while(((schedule.getNoHoursMonth($user)+4)<=(schedule.getNoWorkingDays()*8)) || (schedule.getNoHoursMonth($user)+8)<=(schedule.getNoWorkingDays()*8)){

                Day day =  $day;
                schedule.setSpecificDay(day);
                drools.getKieRuntime().setGlobal("schedule", schedule);
                update($user);
//        }


end

//rule "Replace shifts 3"
//salience 1
//    when $user : User(((schedule.getNoHoursMonth($user)+4)<=(schedule.getNoWorkingDays()*8)) && ((schedule.getNoWorkingDays()*8)-schedule.getNoHoursMonth($user))%4==0);
//         $day: Day(isDateValid()==false) from schedule.selectDayWithShift1($user,ShiftTypes.SHORT.getValue(),ShiftTypes.MORNING.getValue());
//    then
////        while(((schedule.getNoHoursMonth($user)+4)<=(schedule.getNoWorkingDays()*8)) || (schedule.getNoHoursMonth($user)+8)<=(schedule.getNoWorkingDays()*8)){
//
//                Day day = schedule.selectDayWithShift1($user,ShiftTypes.MORNING.getValue(),ShiftTypes.SHORT.getValue());
//                schedule.setSpecificDay(day);
//                drools.getKieRuntime().setGlobal("schedule", schedule);
//                update($user);
////        }
//
//
//end








