package com.hospital.backend.rules;
dialect  "mvel"
import com.hospital.backend.Models.*
import java.util.List
import java.util.Random
import java.util.ArrayList;
global com.hospital.backend.Models.Schedule schedule;

rule "Complete Hours"
   when $user : User(((schedule.getNoHoursMonth8H($user)+8)<=(schedule.getNoWorkingDays()*8)));
    then
            Day dayWithoutUser =schedule.getDayWithoutUser($user);
            List shifts = dayWithoutUser.getShifts();
            Shift newShift = new Shift();
            newShift.setDay(dayWithoutUser);
            newShift.setUser($user);
            ShiftTypes shiftType= schedule.getLessShifts($user);
            newShift.setType(shiftType.getValue());
            shifts.add(newShift);
            dayWithoutUser.setShifts(shifts);
            schedule.setSpecificDay(dayWithoutUser);
            drools.getKieRuntime().setGlobal("schedule", schedule);
            update($user);
end
