package com.hospital.backend.rules;
dialect  "mvel"
import com.hospital.backend.Models.*
import java.util.List;
global com.hospital.backend.Models.Schedule schedule;



rule "Add 12-hour shifts"
salience 7

    when $user : User((schedule.getNoHoursMonth($user)+12)<=(schedule.getNoWorkingDays()*8) && ((schedule.getNoWorkingDays()*8)-schedule.getNoHoursMonth($user))%12==0);
    then
                Day day =schedule.getDayWithoutUser($user);
                List shifts = day.getShifts();
                Shift newShift = new Shift();
                newShift.setDay(day);
                newShift.setUser($user);
                newShift.setType(ShiftTypes.MORNING.getValue());
                shifts.add(newShift);
                day.setShifts(shifts);
                schedule.setSpecificDay(day);
                drools.getKieRuntime().setGlobal("schedule", schedule);
                update($user);


end
rule "Add 8-hour shifts"
salience 5

    when $user : User((schedule.getNoHoursMonth($user)+8)<=(schedule.getNoWorkingDays()*8) && ((schedule.getNoWorkingDays()*8)-schedule.getNoHoursMonth($user))%8==0);
    then
                Day day =schedule.getDayWithoutUser($user);
                List shifts = day.getShifts();
                Shift newShift = new Shift();
                newShift.setDay(day);
                newShift.setUser($user);
                newShift.setType(ShiftTypes.SHORT.getValue());
                shifts.add(newShift);
                day.setShifts(shifts);
                schedule.setSpecificDay(day);
                drools.getKieRuntime().setGlobal("schedule", schedule);
                update($user);


end

