package com.hospital.backend.rules;
import java.time.DayOfWeek;
import com.hospital.backend.Models.*;
import java.time.LocalDate
import java.util.ArrayList
import java.util.Arrays
import java.util.List;
import java.util.Map
import java.util.Collections;
import java.lang.Math;
global java.util.List users;
global com.hospital.backend.Models.Schedule schedule;


dialect  "mvel"

dialect "java"

declare enum DaysOfWeek
   SUN("Sunday"),MON("Monday"),TUE("Tuesday"),WED("Wednesday"),THU("Thursday"),FRI("Friday"),SAT("Saturday");
    fullName : String
end


rule "Add night shifts"
salience 10
lock-on-active
    when
        $day: Day(getNoShifts(ShiftTypes.NIGHT.getValue())<Math.round(users.size()*0.15))
        $nextDay: Day(date==$day.date.plusDays(1) || $day.checkIfLast())

    then
       List shiftList = $day.setNightShifts8H(schedule,users,(int)Math.round(users.size()*0.15),ShiftTypes.NIGHT.getValue(),$nextDay);
       if(!$day.checkIfLast()){
           $nextDay.setFreeDays(shiftList);
           schedule.setSpecificDay($nextDay);
           update($nextDay);
       }

        schedule.setSpecificDay($day);
        update($day);
        drools.getKieRuntime().setGlobal("schedule",schedule);
end
rule "Add morning shifts"
salience 5
lock-on-active
    when
        $day: Day(getNoShifts(ShiftTypes.MORNING.getValue())<Math.round(users.size()*0.20))
    then

        $day.setNoShifts8H(schedule,users,(int)Math.round(users.size()*0.20),ShiftTypes.MORNING.getValue());
        schedule.setSpecificDay($day);
        update($day);
        drools.getKieRuntime().setGlobal("schedule",schedule);


end

rule "Add afternoon shifts"
salience 3
lock-on-active
    when
        $day: Day(getNoShifts(ShiftTypes.AFTERNOON.getValue())<Math.round(users.size()*0.20))
    then

        $day.setNoShifts8H(schedule,users,(int)Math.round(users.size()*0.20),ShiftTypes.AFTERNOON.getValue());
        schedule.setSpecificDay($day);
        update($day);
        drools.getKieRuntime().setGlobal("schedule",schedule);


end




